# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image:
  name: gitlab-registry.in2p3.fr/in2p3_euclid/gacen/dbbuilder_test:v1
stages:
- install
- build
- test
- deploy
variables:
  GIT_SUBMODULE_STRATEGY: normal
install:
  stage: install
  - yum update cmake
build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake -Wno-dev ..
  - make -j $(nproc --all)
  artifacts:
    expire_in: 2 hrs
    paths:
    - build
test:
  stage: test
  script:
  - cd build
  - make test
  - exe/gTest_version
  - exe/gTest_Manager
pages:
  stage: deploy
  script:
  - cd build
  - cmake ..
  - make doc
  - cd ..
  - mv build/doc/html public
  artifacts:
    paths:
    - public
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
